#############################################################################
# Makefile for building: openDB
# Generated by qmake (2.01a) (Qt 4.8.2) on: mar dic 10 22:31:54 2013
# Project:  openDB.git.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile openDB.git.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES) -std=c++11
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/postgresql -Isrc -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread -lpq
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = unitTest.cpp \
		src/column.cpp \
		src/common.cpp \
		src/connection.cpp \
		src/database.cpp \
		src/dbms.cpp \
		src/file_storage.cpp \
		src/insert_table.cpp \
		src/login_dialog.cpp \
		src/memory_storage.cpp \
		src/queryAttribute.cpp \
		src/record.cpp \
		src/schema.cpp \
		src/sqlType.cpp \
		src/table.cpp \
		src/update_table.cpp \
		src/view.cpp moc_insert_table.cpp \
		moc_login_dialog.cpp \
		moc_update_table.cpp
OBJECTS       = unitTest.o \
		column.o \
		common.o \
		connection.o \
		database.o \
		dbms.o \
		file_storage.o \
		insert_table.o \
		login_dialog.o \
		memory_storage.o \
		queryAttribute.o \
		record.o \
		schema.o \
		sqlType.o \
		table.o \
		update_table.o \
		view.o \
		moc_insert_table.o \
		moc_login_dialog.o \
		moc_update_table.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		openDB.git.pro
QMAKE_TARGET  = openDB
DESTDIR       = 
TARGET        = openDB

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: openDB.git.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile openDB.git.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile openDB.git.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/openDB1.0.0 || $(MKDIR) .tmp/openDB1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/openDB1.0.0/ && $(COPY_FILE) --parents src/column.hpp src/common.hpp src/connection.hpp src/database.hpp src/dbms.hpp src/exception.hpp src/file_storage.hpp src/insert_table.hpp src/login_dialog.hpp src/memory_storage.hpp src/queryAttribute.hpp src/record.hpp src/schema.hpp src/sqlType.hpp src/storage.hpp src/table.hpp src/update_table.hpp src/view.hpp .tmp/openDB1.0.0/ && $(COPY_FILE) --parents unitTest.cpp src/column.cpp src/common.cpp src/connection.cpp src/database.cpp src/dbms.cpp src/file_storage.cpp src/insert_table.cpp src/login_dialog.cpp src/memory_storage.cpp src/queryAttribute.cpp src/record.cpp src/schema.cpp src/sqlType.cpp src/table.cpp src/update_table.cpp src/view.cpp .tmp/openDB1.0.0/ && (cd `dirname .tmp/openDB1.0.0` && $(TAR) openDB1.0.0.tar openDB1.0.0 && $(COMPRESS) openDB1.0.0.tar) && $(MOVE) `dirname .tmp/openDB1.0.0`/openDB1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/openDB1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_insert_table.cpp moc_login_dialog.cpp moc_update_table.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_insert_table.cpp moc_login_dialog.cpp moc_update_table.cpp
moc_insert_table.cpp: src/insert_table.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/insert_table.hpp -o moc_insert_table.cpp

moc_login_dialog.cpp: src/login_dialog.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/login_dialog.hpp -o moc_login_dialog.cpp

moc_update_table.cpp: src/update_table.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/update_table.hpp -o moc_update_table.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

unitTest.o: unitTest.cpp src/database.hpp \
		src/schema.hpp \
		src/table.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/memory_storage.hpp \
		src/file_storage.hpp \
		src/dbms.hpp \
		src/connection.hpp \
		src/login_dialog.hpp \
		src/insert_table.hpp \
		src/update_table.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unitTest.o unitTest.cpp

column.o: src/column.cpp src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o column.o src/column.cpp

common.o: src/common.cpp src/common.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o common.o src/common.cpp

connection.o: src/connection.cpp src/connection.hpp \
		src/table.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/memory_storage.hpp \
		src/file_storage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connection.o src/connection.cpp

database.o: src/database.cpp src/database.hpp \
		src/schema.hpp \
		src/table.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/memory_storage.hpp \
		src/file_storage.hpp \
		src/dbms.hpp \
		src/connection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o src/database.cpp

dbms.o: src/dbms.cpp src/dbms.hpp \
		src/connection.hpp \
		src/table.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/memory_storage.hpp \
		src/file_storage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbms.o src/dbms.cpp

file_storage.o: src/file_storage.cpp src/file_storage.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o file_storage.o src/file_storage.cpp

insert_table.o: src/insert_table.cpp src/insert_table.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o insert_table.o src/insert_table.cpp

login_dialog.o: src/login_dialog.cpp src/login_dialog.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login_dialog.o src/login_dialog.cpp

memory_storage.o: src/memory_storage.cpp src/memory_storage.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memory_storage.o src/memory_storage.cpp

queryAttribute.o: src/queryAttribute.cpp src/queryAttribute.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queryAttribute.o src/queryAttribute.cpp

record.o: src/record.cpp src/record.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/common.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o record.o src/record.cpp

schema.o: src/schema.cpp src/schema.hpp \
		src/table.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/memory_storage.hpp \
		src/file_storage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o schema.o src/schema.cpp

sqlType.o: src/sqlType.cpp src/sqlType.hpp \
		src/exception.hpp \
		src/common.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlType.o src/sqlType.cpp

table.o: src/table.cpp src/table.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/memory_storage.hpp \
		src/file_storage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table.o src/table.cpp

update_table.o: src/update_table.cpp src/update_table.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o update_table.o src/update_table.cpp

view.o: src/view.cpp src/view.hpp \
		src/table.hpp \
		src/column.hpp \
		src/sqlType.hpp \
		src/exception.hpp \
		src/queryAttribute.hpp \
		src/storage.hpp \
		src/record.hpp \
		src/memory_storage.hpp \
		src/file_storage.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o src/view.cpp

moc_insert_table.o: moc_insert_table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_insert_table.o moc_insert_table.cpp

moc_login_dialog.o: moc_login_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login_dialog.o moc_login_dialog.cpp

moc_update_table.o: moc_update_table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_update_table.o moc_update_table.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

